In [1]:
import matplotlib
import numpy as np
import csv

In [2]:
header = None
array = np.empty((0,11))
print(array.ndim)
print
with open('image_quality.csv', newline='') as csvfile:
    reader = csv.reader(csvfile, delimiter=',')
    header =  next(reader)
    #print(header)
    for line in reader:
        array = np.append(array, [line], axis=0)

2


In [3]:
# Contain all read data in separate objects
class NetworkData:
    def __init__(self, name: str, data: np.ndarray, datalabels: np.ndarray):
        self.name = name
        self.data = data
        self.datalabels = datalabels
        self.stats = np.mean(data, axis=0)

In [4]:
# Get unique networks
networks = np.unique(array[:,3])
print(networks)
print (header[4:])

['DenseNet' 'GoogleNet' 'ResNet' 'SqueezeNet' 'VGG']
['fsim', 'lpips', 'psnr', 'ssim', 'brisque', 'niqe', 'piqe']


In [5]:
data_collection = []

In [6]:
for net in networks:
    name = net;
    rawdata = array[array[:,3] == net]
    data = rawdata[:,4:].astype(float)
    datalabels = rawdata[:,0:4]
    obj = NetworkData(name, data, datalabels)
    data_collection.append(obj)

In [49]:
#Preview Data
print(header[4:8])
for x in data_collection:
    print(x.stats[0:4], x.name)

print(header[8:])
for x in data_collection:
    print(x.stats[4:], x.name)

['fsim', 'lpips', 'psnr', 'ssim']
[ 0.74698207  0.58804029 11.50707357  0.40726548] DenseNet
[ 0.65997757  0.69004036 10.32890771  0.16571217] GoogleNet
[ 0.7659732   0.54137451 11.37940849  0.41752719] ResNet
[ 0.79345603  0.55754215 14.7078939   0.30730898] SqueezeNet
[ 0.81526032  0.51999968 13.85936687  0.48935377] VGG
['brisque', 'niqe', 'piqe']
[43.14632314  6.52110172 46.21060197] DenseNet
[72.76464895 15.59353564 67.60636853] GoogleNet
[54.03096059  6.90023952 52.25544847] ResNet
[72.60496216 13.33427292 62.76677184] SqueezeNet
[72.96802057 15.8020476  54.20533355] VGG


In [48]:
#Export Image Data
with open('image_analysis.csv', 'w', newline='') as csvfile:
    csvwriter = csv.writer(csvfile)
    csvwriter.writerow(header[3:])
    for x in data_collection:
        stats = np.concatenate(([x.name],x.stats))
        csvwriter.writerow(stats)