In [17]:
import matplotlib
import numpy as np
import csv

In [18]:
header = None
array = np.empty((0,11))
print(array.ndim)
print
with open('iqs_VG.csv', newline='') as csvfile:
    reader = csv.reader(csvfile, delimiter=',')
    header =  next(reader)
    #print(header)
    for line in reader:
        array = np.append(array, [line], axis=0)

2


In [19]:
# Contain all read data in separate objects
class NetworkData:
    def __init__(self, name: str, data: np.ndarray, datalabels: np.ndarray):
        self.name = name
        self.data = data
        self.datalabels = datalabels
        self.stats = np.mean(data, axis=0)

In [20]:
# Get unique networks
networks = np.unique(array[:,3])
print(networks)
print (header[4:])

['DenseNet' 'GoogleNet' 'ResNet' 'SqueezeNet' 'VGG']
['fsim', 'lpips', 'psnr', 'ssim', 'brisque', 'niqe', 'piqe']


In [21]:
data_collection = []

In [22]:
for net in networks:
    name = net;
    rawdata = array[array[:,3] == net]
    data = rawdata[:,4:].astype(float)
    datalabels = rawdata[:,0:4]
    obj = NetworkData(name, data, datalabels)
    data_collection.append(obj)

In [23]:
#Preview Data
print(header[4:8])
for x in data_collection:
    print(x.stats[0:4], x.name)

print(header[8:])
for x in data_collection:
    print(x.stats[4:], x.name)

['fsim', 'lpips', 'psnr', 'ssim']
[ 0.80818962  0.44392222 15.42075753  0.55160521] DenseNet
[ 0.83319622  0.39837445 15.63246083  0.53482243] GoogleNet
[ 0.83997187  0.33732405 18.99799919  0.68699755] ResNet
[ 0.83864106  0.38709911 17.08577299  0.53587143] SqueezeNet
[ 0.82913299  0.38908079 17.72900581  0.68525062] VGG
['brisque', 'niqe', 'piqe']
[29.79388428  4.56196561 37.10438251] DenseNet
[13.13026428  4.99235015 48.52858639] GoogleNet
[15.07119751  3.63361433 23.55344868] ResNet
[ 9.51255798  4.86913903 49.60888767] SqueezeNet
[19.4072876   3.78814863 23.42786455] VGG


In [24]:
#Export Image Data
with open('image_analysVG.csv', 'w', newline='') as csvfile:
    csvwriter = csv.writer(csvfile)
    csvwriter.writerow(header[3:])
    for x in data_collection:
        stats = np.concatenate(([x.name],x.stats))
        csvwriter.writerow(stats)